export const contractKpi = [
  {
    id: 135,
    name: 'Nghiên cứu kỹ HSMT và BV kỹ thuật thi công',
    parentId: 1,
    contactId: 123,
    titleType: 21,
    subject: '',
    description: '',
    contact: {
      id: 1,
      issueId: 101,
      fullname: 'Nguyen Van A',
      phone: '0123456789',
      email: 'nguyenvana@example.com',
      userId: 'user001',
      employeeId: 123,
      employeeCode: 456,
      status: 1,
      issueCreateBys: ['user002', 'user003'],
      issueAssigneds: ['user004'],
      issueContacts: [],
      issue: 'Issue 1'
    },
    startDate: '2023/12/12',
    dueDate: '2023/12/12',
    actualStartDate: '2023/12/12',
    actualEndDate: '2023/12/12',
    assignedTo: {
      id: 2,
      issueId: 102,
      fullname: 'Tran Thi B',
      phone: '0987654321',
      email: 'tranthib@example.com',
      userId: 'user005',
      employeeId: 124,
      employeeCode: 457,
      status: 2,
      issueCreateBys: ['user006'],
      issueAssigneds: ['user007', 'user008'],
      issueContacts: [],
      issue: 'Issue 2'
    },
    supervisor: {
      id: 0,
      fullname: '',
      phone: ''
    },
    attachmentLinks: 'gdfs',
    progress: 123213,
    note: 'string',
    tagVersionId: 1231, // Giai đoạn của Issue
    nature:  123,
    status: 2,
    children: []
  },
  {
    id: 13245,
    name: 'Nghiên cứu kỹ HSMT và BV kỹ thuật thi công',
    parentId: 1,
    contactId: 123,
    titleType: 21,
    subject: '',
    description: '',
    contact: {
      id: 1,
      issueId: 101,
      fullname: 'Nguyen Van A',
      phone: '0123456789',
      email: 'nguyenvana@example.com',
      userId: 'user001',
      employeeId: 123,
      employeeCode: 456,
      status: 1,
      issueCreateBys: ['user002', 'user003'],
      issueAssigneds: ['user004'],
      issueContacts: [],
      issue: 'Issue 1'
    },
    startDate: '2023/12/12',
    dueDate: '2023/12/12',
    actualStartDate: '2023/12/12',
    actualEndDate: '2023/12/12',
    assignedTo: {
      id: 2,
      issueId: 102,
      fullname: 'Tran Thi B',
      phone: '0987654321',
      email: 'tranthib@example.com',
      userId: 'user005',
      employeeId: 124,
      employeeCode: 457,
      status: 2,
      issueCreateBys: ['user006'],
      issueAssigneds: ['user007', 'user008'],
      issueContacts: [],
      issue: 'Issue 2'
    },
    supervisor: {
      id: 0,
      fullname: '',
      phone: ''
    },
    attachmentLinks: 'gdfs',
    progress: 123213,
    note: 'string',
    tagVersionId: 1231, // Giai đoạn của Issue
    nature:  123,
    status: 2,
    children: []
  },
  {
    id: 15,
    name: 'Nghiên cứu kỹ HSMT và BV',
    parentId: 1,
    contactId: 123,
    titleType: 21,
    subject: '',
    description: '',
    contact: {
      id: 1,
      issueId: 101,
      fullname: 'Nguyen Van A',
      phone: '0123456789',
      email: 'nguyenvana@example.com',
      userId: 'user001',
      employeeId: 123,
      employeeCode: 456,
      status: 1,
      issueCreateBys: ['user002', 'user003'],
      issueAssigneds: ['user004'],
      issueContacts: [],
      issue: 'Issue 1'
    },
    startDate: '2023/12/12',
    dueDate: '2023/12/12',
    actualStartDate: '2023/12/12',
    actualEndDate: '2023/12/12',
    assignedTo: {
      id: 2,
      issueId: 102,
      fullname: 'Tran Thi B',
      phone: '0987654321',
      email: 'tranthib@example.com',
      userId: 'user005',
      employeeId: 124,
      employeeCode: 457,
      status: 2,
      issueCreateBys: ['user006'],
      issueAssigneds: ['user007', 'user008'],
      issueContacts: [],
      issue: 'Issue 2'
    },
    supervisor: {
      id: 0,
      fullname: '',
      phone: ''
    },
    attachmentLinks: 'gdfs',
    progress: 123213,
    note: 'string',
    tagVersionId: 1231, // Giai đoạn của Issue
    nature:  123,
    status: 2,
    children: [
      {
            id: 135,
        name: 'Nghiên cứu kỹ HSMT và BV kỹ thuật thi công',
        parentId: 1,
        contactId: 123,
        titleType: 21,
        subject: '',
        description: '',
        contact: {
          id: 1,
          issueId: 101,
          fullname: 'Nguyen Van A',
          phone: '0123456789',
          email: 'nguyenvana@example.com',
          userId: 'user001',
          employeeId: 123,
          employeeCode: 456,
          status: 1,
          issueCreateBys: ['user002', 'user003'],
          issueAssigneds: ['user004'],
          issueContacts: [],
          issue: 'Issue 1'
        },
        startDate: '2023/12/12',
        dueDate: '2023/12/12',
        actualStartDate: '2023/12/12',
        actualEndDate: '2023/12/12',
        assignedTo: {
          id: 2,
          issueId: 102,
          fullname: 'Tran Thi B',
          phone: '0987654321',
          email: 'tranthib@example.com',
          userId: 'user005',
          employeeId: 124,
          employeeCode: 457,
          status: 2,
          issueCreateBys: ['user006'],
          issueAssigneds: ['user007', 'user008'],
          issueContacts: [],
          issue: 'Issue 2'
        },
        supervisor: {
          id: 0,
          fullname: '',
          phone: ''
        },
        attachmentLinks: 'gdfs',
        progress: 123213,
        note: 'string',
        tagVersionId: 1231, // Giai đoạn của Issue
        nature:  123,
        status: 2,
        children: []
      }
    ]
  },
];